spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.249.197:3306/hzwd?serverTimezone=GMT%2B8
    username: root
    password: root
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
server:
  port: 8887
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 3000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yxr.hz.entity
mvc:
  hiddenmethod:
    filter:
      enabled: true
session:
  setMaxInactiveInterval: 30*60
logging:
  file:
    name: logs/log.log
